import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Toaster } from "sonner";
import Script from "next/script";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  adjustFontFallback: "Arial",
  fallback: [
    "Apple SD Gothic Neo",
    "Malgun Gothic",
    "Noto Sans KR",
    "Segoe UI",
    "Helvetica",
    "sans-serif",
  ],
  weight: "45 920",
  variable: "--font-pretendard",
});

const baseUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : "http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: {
    default: "BAEK SEJIN",
    template: "%s - BAEK SEJIN",
  },
  description: "Generated by baek sejin",
  openGraph: {
    type: "website",
    siteName: "BAEK SEJIN",
    images: ["/og/default.webp"],
  },
  twitter: { card: "summary_large_image", images: ["/og/default.webp"] },
  robots: { index: true, follow: true },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <head>
        {/*  GA4 */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-ZZY0C2ZG54"
        ></Script>
        <Script id="ga4-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-ZZY0C2ZG54');
          `}
        </Script>
      </head>
      <body className={pretendard.className}>
        <Header />
        <main id="main-content" tabIndex={-1}>
          {children}
        </main>
        <Footer />
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
