import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RouteMargin from "../components/RouteMargin";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Toaster } from "sonner";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  adjustFontFallback: "Arial",
  fallback: [
    "Apple SD Gothic Neo",
    "Malgun Gothic",
    "Noto Sans KR",
    "Segoe UI",
    "Helvetica",
    "Arial",
    "sans-serif",
  ],
  weight: "45 920",
  variable: "--font-pretendard",
});

const baseUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : "http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: {
    default: "BAEK SEJIN",
    template: "%s - BAEK SEJIN",
  },
  description: "Generated by baek sejin",
  openGraph: {
    type: "website",
    siteName: "BAEK SEJIN",
    images: ["/og/default.webp"],
  },
  twitter: { card: "summary_large_image", images: ["/og/default.webp"] },
  robots: { index: true, follow: true },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className={pretendard.className}>
        <Header />
        <main id="main-content" tabIndex={-1}>
          <RouteMargin>{children}</RouteMargin>
        </main>
        <Footer />
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
