import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Toaster } from "sonner";
import RouteMargin from "../components/RouteMargin";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
  preload: true,
});

export const metadata: Metadata = {
  title: "BAEK SEJIN",
  description: "Generated by baek sejin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <Header />
        <Toaster position="top-center" />
        <RouteMargin>{children}</RouteMargin>
        <Footer />
      </body>
    </html>
  );
}
